### ISSUE TITLE
更新完成度数字溢出

### ISSUE THREAD

**Issue by jsyzdej** [DinoChan/Loaf#2]
摸鱼的时候发现数字溢出了
![image](https://user-images.githubusercontent.com/13121137/146336930-b7480e4f-dca1-40a7-bf91-54ab16e2fa89.png)

**Comment by hehua04** [comment]
看图片，还有个问题，懒得开新issue了，turn off让你写成turn of了，少个f。

**Comment by hifocus** [comment]
![image](https://user-images.githubusercontent.com/30528433/146407845-f83fd013-e690-4b79-adb2-8561760b5d1e.png)
就很尴尬

**Comment by hifocus** [comment]
![image](https://user-images.githubusercontent.com/30528433/146407932-ec7442c6-69cf-4140-b298-a4d7e55a3126.png)
非常恐怖 兄弟

**Comment by hehua04** [comment]
我说的好像还没改， #6
