### ISSUE TITLE
希望能够汉化一下应用的名称——摸鱼

### ISSUE THREAD

**Issue by Gaoyifei1011** [DinoChan/Loaf#20]
目前应用在开始菜单显示的应用名称为Loaf - winui3 app，希望能够汉化一下应用名称——摸鱼
![图片](https://user-images.githubusercontent.com/49179966/146711756-62039091-1ae3-4292-845e-56eee7c87f68.png)

**Comment by DinoChan** [comment]
在 #25 中处理了
