### ISSUE TITLE
支持Windows11的更新样式

### ISSUE THREAD

**Issue by HinataKato** [DinoChan/Loaf#3]
如题

**Comment by BattleOil** [comment]
这就是 Windows 11 的更新页面。微软为了和 Windows 10 的更新页面区分开来，Windows 11 的更新页面已经改成纯黑背景而非跟随系统主题色了。

**Comment by HinataKato** [comment]
> 这就是 Windows 11 的更新页面。微软为了和 Windows 10 的更新页面区分开来，Windows 11 的更新页面已经改成纯黑背景而非跟随系统主题色了。

不是跟随主题色的问题 是我记得之前看到过 你已完成xx% 可能是正式版改翻译了？

**Comment by Wenti-D** [comment]
> 

在我更新 Win 11 的时候，屏幕上显示的话就是

> 　正在进行更新 xx%
> 请保持计算机打开状态。
> 
> 
> 计算机可能会重启几次。

**Comment by HinataKato** [comment]
我确认了一下 确实是

> > 正在进行更新 xx%
> > 请保持计算机打开状态。
> > 计算机可能会重启几次。
