### ISSUE TITLE
输入法工具栏无法隐藏

### ISSUE THREAD

**Issue by include-nan** [DinoChan/Loaf#35]
系统版本：Win 11 21H1 22000.434
Windows 自带输入法开启工具栏无法隐藏
![image](https://user-images.githubusercontent.com/48525815/149071453-547e4091-c3c4-478d-9600-355e8afe6655.png)

**Comment by xvzhenduo** [comment]
用topmost将这个窗口置顶，可以挡住

**Comment by include-nan** [comment]
感谢分享
