### ISSUE TITLE
有没有Mac版的呢？

### ISSUE THREAD

**Issue by APushingBoy** [DinoChan/Loaf#7]
公司里有时候会用Mac，有没有Mac版的呢？

**Comment by DinoChan** [comment]
没有。你可以直接用 fakeupdate.net/

**Comment by Co2333** [comment]
https://github.com/Co2333/FishUpgrade

**Comment by srxboys** [comment]
https://sourceforge.net/projects/loaf-rx/

electron+vue2

凑个热闹
